import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="flex justify-center">
          <Image
            src="/logo.png"
            alt="Vercel Logo"
            width={200}
            height={100}
            priority
          />
        </header>
        <main className="container mx-auto">{children}</main>
      </body>
    </html>
  );
}
